### ISSUE TITLE
Display human readable date instead of unix timestamp

### ISSUE THREAD

**Issue by xuqingfeng** [xuqingfeng/TopHackerNews#2]
File to update: https://github.com/xuqingfeng/TopHackerNews/blob/main/web/src/lib/Stories.svelte

**Comment by Shubh8899** [comment]
I would like to work on this one.

**Comment by xuqingfeng** [comment]
@Shubh8899 Let know if you still want to tackle this issue.

**Comment by Shubh8899** [comment]
@xuqingfeng  yes, i am setting up the repo & would like to work on this.

**Comment by xuqingfeng** [comment]
OK, ping me if you need help.
